name: CI: Build, Push & SES Notify

on:
  push:
    branches:
      - '**'

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:latest -t $IMAGE:${{ steps.vars.outputs.sha_short }} .

  push:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag existing image for push
        run: |
          docker tag $IMAGE:latest $IMAGE:latest
          docker tag $IMAGE:${{ needs.build.outputs.sha_short }} $IMAGE:${{ needs.build.outputs.sha_short }}

      - name: Push
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:${{ needs.build.outputs.sha_short }}

  notify:
    name: Notify via SES
    needs: [build, push]
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification (on success)
        if: success()
        run: |
          aws ses send-email \
            --from 'saravana.rockz8@gmail.com' \
            --destination 'ToAddresses="saravanak3786@gmail.com"' \
            --message 'Subject={Data="✅ Build Success - ${{ github.repository }}"},Body={Text={Data="Build for ${{ github.repository }} on branch `${{ github.ref_name}}` was successful!\n\nCommit: `${{ github.sha}}`\nWorkflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region Europe (Stockholm)

      - name: Send Email Notification (on failure)
        if: failure()
        run: |
          aws ses send-email \
            --from 'saravana.rockz8@gmail.com \
            --destination 'ToAddresses="saravanak3786@gmail.com"' \
            --message 'Subject={Data="❌ Build FAILED - ${{ github.repository }}"},Body={Text={Data="*ALERT:* Build for ${{ github.repository }} on branch `${{ github.ref_name}}` *FAILED!*\n\nCommit: `${{ github.sha}}`\n*Please review logs:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region Europe (Stockholm)
